project:
  type: website
  output-dir: docs
  resources:
    - content/

website:
  title: "Emilio SÃ¡nchez"
  navbar:
    # logo: content/logo.png
    logo-alt: ESA99 Logo
    left:
      # - href: index.qmd
      #   text: Home
      - text: "Projects"
        href: pages/projects.qmd
      - text: "Resources"
        menu:
          - text: "Overview"  
            href: pages/resources.qmd
          - text: "Virtual Environments"
            href: pages/resources/VirtualEnvs.qmd
      # - href: CV.qmd
      #   text: CV
      # #- about.qmd
    right: 
      - text: "CV"
        href: pages/CV.qmd
      # - text: "About"
      #   href: pages/about.qmd
    tools:
      - href: https://github.com/ESA99
        icon: github
    search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header:
     text: |
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.1/css/academicons.min.css">


